version: '3.8'

services:
  reverse-proxy:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    networks:
      - application-node
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.:/workspace:cached
    command: sleep infinity
    networks:
      - application-node

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - application-node
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
networks:
  application-node:
